#!/usr/bin/env bash
# build_layout.sh — clean rebuild of lsdl_inv_x1 layout.
#
# Removes stale FET subcell .mag files (so Magic doesn't auto-load
# previous geometry), runs the Magic TCL script to regenerate the
# top cell, then renders a PNG via KLayout headless.
#
# Files regenerated by this run:
#   - <fet_subcells>.mag       (7 unique W/L subcells)
#   - lsdl_inv_x1.mag
#   - lsdl_inv_x1.gds
#   - lsdl_inv_x1.png

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CELL_DIR="${ROOT}/cells/lsdl_basic"
LOG_DIR="/soe/czeng14/projects/brainstorm-domino-tmp"
mkdir -p "${LOG_DIR}"

# Remove stale Magic-managed cells so cellname create gets a clean slate.
rm -f "${CELL_DIR}"/pfet_W*_L*.mag "${CELL_DIR}"/nfet_W*_L*.mag \
      "${CELL_DIR}/lsdl_inv_x1.mag" "${CELL_DIR}/lsdl_inv_x1.gds"

# Run Magic TCL inside the container.
"${ROOT}/scripts/run_in_container.sh" \
    "magic -dnull -noconsole \
       -rcfile /soe/czeng14/software/pdk/gf180mcuD/libs.tech/magic/gf180mcuD.magicrc \
       -T gf180mcuD \
       ${CELL_DIR}/lsdl_inv_x1_layout.tcl" \
    > "${LOG_DIR}/layout_run.log" 2>&1

# Add unified DUALGATE + FET5VDEF markers to the GDS (Magic auto-derives
# DUALGATE per-FET but the fragments don't merge for wide cells; the
# stock library uses single rectangles).
"${ROOT}/scripts/run_in_container.sh" \
    "python3 ${ROOT}/scripts/postprocess_gds.py \
        ${CELL_DIR}/lsdl_inv_x1.gds \
        ${CELL_DIR}/lsdl_inv_x1.gds" \
    >> "${LOG_DIR}/layout_run.log" 2>&1

# Render the resulting GDS to PNG.
"${ROOT}/scripts/run_in_container.sh" \
    "python3 ${ROOT}/scripts/render_gds.py \
        ${CELL_DIR}/lsdl_inv_x1.gds \
        ${CELL_DIR}/lsdl_inv_x1.png" \
    > "${LOG_DIR}/render_run.log" 2>&1

echo "==== layout summary ===="
grep -E "built|placed|paint|====|errors|  -" "${LOG_DIR}/layout_run.log" || true
echo
echo "==== outputs ===="
ls -la "${CELL_DIR}/lsdl_inv_x1.mag" "${CELL_DIR}/lsdl_inv_x1.gds" \
       "${CELL_DIR}/lsdl_inv_x1.png" 2>/dev/null || true
