#!/usr/bin/env python3
"""gen_liberty.py — generate Liberty (.lib) for LSDL cells.

Reads cell descriptor YAML + PVT sweep JSON, emits a scalar (single
operating condition) Liberty file. LSDL cells are modelled as positive-
edge-triggered flops: ff(IQ,IQN) {clocked_on:CLK; next_state:<fn>;}.

Usage:
  # Single cell (produces cells/lsdl_basic/<cell>.lib):
  gen_liberty.py descriptor/lsdl_nand2_x1.yaml

  # All cells -> combined library file:
  gen_liberty.py --all --output lib/lsdl_fd_sc_9t5v0__tt_5v_25c.lib

PVT JSON is loaded from $PVT_DIR/<cell>_pvt.json (default:
/soe/czeng14/projects/brainstorm-domino-tmp/pvt_sweep/).
If absent, conservative fallback delays are used and a warning is printed.
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path
import yaml

# ── paths ────────────────────────────────────────────────────────────────────
LSDL_LIB  = Path(__file__).resolve().parents[1]
DESC_DIR  = LSDL_LIB / 'descriptor'
PVT_DIR   = LSDL_LIB / 'pvt'   # durable JSON summaries (version-controlled)

# conservative fallback delays (ns) if no PVT JSON is present.
# Over-estimated to be timing-safe at SS/125°C.
FALLBACK_CELL_FALL_NS = {
    'lsdl_inv_x1':    0.250,
    'lsdl_nand2_x1':  0.280,
    'lsdl_nand3_x1':  0.330,
    'lsdl_nand4_x1':  0.380,
    'lsdl_nor2_x1':   0.260,
    'lsdl_nor3_x1':   0.280,
    'lsdl_nor4_x1':   0.310,
    'lsdl_aoi21_x1':  0.310,
    'lsdl_aoi22_x1':  0.360,
}

# Cell sizes from LEF (width µm × 6.16 µm height).
CELL_AREA = {
    'lsdl_inv_x1':    13.44 * 6.16,
    'lsdl_nand2_x1':  15.12 * 6.16,
    'lsdl_nand3_x1':  16.80 * 6.16,
    'lsdl_nand4_x1':  18.48 * 6.16,
    'lsdl_nor2_x1':   15.12 * 6.16,
    'lsdl_nor3_x1':   16.80 * 6.16,
    'lsdl_nor4_x1':   18.48 * 6.16,
    'lsdl_aoi21_x1':  16.80 * 6.16,
    'lsdl_aoi22_x1':  18.48 * 6.16,
}


# ── helpers ──────────────────────────────────────────────────────────────────
def load_pvt(cell: str) -> dict | None:
    p = PVT_DIR / f'{cell}_pvt.json'
    if not p.exists():
        return None
    with open(p) as f:
        return json.load(f)


def tt_25_5v_delay(pvt: dict) -> float | None:
    """Return the TT / 25 °C / 5.0 V propagation delay in nanoseconds.

    Looks for whichever timing key exists (tpd_eval_lh for INV,
    tpd_eval_hl for all others).
    """
    TPD_KEYS = ('tpd_eval_hl', 'tpd_eval_lh')
    for entry in pvt.get('results', []):
        if (entry.get('corner') in ('typical', 'tt')
                and abs(entry.get('temp_c', 999) - 25) < 1
                and abs(entry.get('vdd_v', 0) - 5.0) < 0.01):
            meas = entry.get('meas', {})
            for key in TPD_KEYS:
                if key in meas and meas[key] is not None:
                    return abs(meas[key]) * 1e9   # s → ns
    return None


def worst_case_delay(pvt: dict) -> float | None:
    """Return the worst-case (max tpd across all PVT points) in nanoseconds."""
    TPD_KEYS = ('tpd_eval_hl', 'tpd_eval_lh')
    worst = None
    for entry in pvt.get('results', []):
        meas = entry.get('meas', {})
        for key in TPD_KEYS:
            v = meas.get(key)
            if v is not None:
                v_ns = abs(v) * 1e9
                if worst is None or v_ns > worst:
                    worst = v_ns
    return worst


# ── Liberty emitters ─────────────────────────────────────────────────────────
_HEADER = """\
/* lsdl_fd_sc_9t5v0 — LSDL standard-cell library, GF180MCU 5V.
 * Generated by gen_liberty.py. Single operating condition: TT 5.0V 25C.
 * Scalar (single-value) timing — conservative first pass.
 * Full PVT lookup tables deferred to L5-B after adder STA validation.
 */
library (lsdl_fd_sc_9t5v0) {

  technology (cmos);
  delay_model : table_lookup;
  nom_process : 1.0;
  nom_voltage : 5.00;
  nom_temperature : 25.0;

  /* units */
  time_unit : "1ns";
  voltage_unit : "1V";
  current_unit : "1mA";
  pulling_resistance_unit : "1kohm";
  leakage_power_unit : "1nW";
  capacitive_load_unit (1, pf);

  /* default thresholds (50% crossings) */
  input_threshold_pct_rise  : 50.0;
  input_threshold_pct_fall  : 50.0;
  output_threshold_pct_rise : 50.0;
  output_threshold_pct_fall : 50.0;
  slew_lower_threshold_pct_rise : 10.0;
  slew_upper_threshold_pct_rise : 90.0;
  slew_lower_threshold_pct_fall : 10.0;
  slew_upper_threshold_pct_fall : 90.0;

  /* default wire load (negligible — PnR provides actual RC) */
  default_fanout_load      : 1.0;
  default_inout_pin_cap    : 0.005;
  default_input_pin_cap    : 0.005;
  default_output_pin_cap   : 0.000;
  default_max_transition   : 0.500;

  operating_conditions (tt_5v_25c) {
    process     : 1.0;
    voltage     : 5.0;
    temperature : 25.0;
  }
  default_operating_conditions : tt_5v_25c;

"""

_FOOTER = "}\n"


def emit_cell(desc: dict, cell_fall_ns: float, min_pw_high_ns: float) -> str:
    """Return the Liberty text for one cell (without library wrapper)."""
    name     = desc['name']
    function = desc['function']
    pins     = desc['pins']
    area     = CELL_AREA.get(name, 0.0)

    # classify pins
    clk_name   = next(p['name'] for p in pins if p.get('is_clock'))
    data_inputs = [p['name'] for p in pins
                   if p['direction'] == 'input' and not p.get('is_clock')]
    outputs    = [p['name'] for p in pins if p['direction'] == 'output']
    pwr_pins   = [p for p in pins if p['direction'] in ('power', 'ground')]

    cell_rise_ns = 0.050    # precharge fast path (conservative constant)
    setup_ns     = 0.100    # conservative setup
    hold_ns      = 0.050    # conservative hold
    min_pw_low   = 0.250    # precharge window minimum

    lines = []
    L = lines.append
    L(f'  cell ({name}) {{')
    L(f'    area : {area:.2f};')
    L(f'    /* Out = {function} — registers on {clk_name} rising edge */')
    L('')

    # clock pin
    L(f'    pin ({clk_name}) {{')
    L(f'      direction : input;')
    L(f'      clock     : true;')
    L(f'      capacitance : 0.010;')
    L(f'      min_pulse_width_high : {min_pw_high_ns:.3f};')
    L(f'      min_pulse_width_low  : {min_pw_low:.3f};')
    L(f'    }}')

    # data input pins
    for inp in data_inputs:
        L(f'    pin ({inp}) {{')
        L(f'      direction   : input;')
        L(f'      capacitance : 0.005;')
        L(f'      timing () {{')
        L(f'        related_pin   : "{clk_name}";')
        L(f'        timing_type   : setup_rising;')
        L(f'        rise_constraint (scalar) {{ values ("{setup_ns:.3f}"); }}')
        L(f'        fall_constraint (scalar) {{ values ("{setup_ns:.3f}"); }}')
        L(f'      }}')
        L(f'      timing () {{')
        L(f'        related_pin   : "{clk_name}";')
        L(f'        timing_type   : hold_rising;')
        L(f'        rise_constraint (scalar) {{ values ("{hold_ns:.3f}"); }}')
        L(f'        fall_constraint (scalar) {{ values ("{hold_ns:.3f}"); }}')
        L(f'      }}')
        L(f'    }}')

    # ff state element
    L(f'    ff ("IQ", "IQN") {{')
    L(f'      clocked_on : "{clk_name}";')
    L(f'      next_state : "{function}";')
    L(f'    }}')

    # output pin
    for out in outputs:
        L(f'    pin ({out}) {{')
        L(f'      direction : output;')
        L(f'      function  : "IQ";')
        L(f'      timing () {{')
        L(f'        related_pin : "{clk_name}";')
        L(f'        timing_type : rising_edge;')
        L(f'        /* cell_fall = evaluate path (n-tree discharges, Out falls) */')
        L(f'        cell_fall (scalar) {{ values ("{cell_fall_ns:.3f}"); }}')
        L(f'        /* cell_rise = precharge+non-eval path (conservative = same) */')
        L(f'        cell_rise (scalar) {{ values ("{cell_rise_ns:.3f}"); }}')
        L(f'        fall_transition (scalar) {{ values ("0.040"); }}')
        L(f'        rise_transition (scalar) {{ values ("0.040"); }}')
        L(f'      }}')
        L(f'    }}')

    # power/ground pins
    for p in pwr_pins:
        ptype = 'primary_power' if p['direction'] == 'power' else 'primary_ground'
        L(f'    pin ({p["name"]}) {{')
        L(f'      direction : inout;')
        L(f'      pg_type   : {ptype};')
        L(f'    }}')

    L(f'    cell_leakage_power : 0.100;')
    L(f'  }}')
    return '\n'.join(lines) + '\n'


# ── per-cell dispatch ─────────────────────────────────────────────────────────
def process_cell(desc_path: Path, *, pvt_dir: Path = PVT_DIR) -> tuple[str, str, Path]:
    """Load descriptor, derive timing, return (cell_name, liberty_text, out_path)."""
    with open(desc_path) as f:
        desc = yaml.safe_load(f)
    name = desc['name']

    pvt  = load_pvt(name)
    cell_fall_ns = None
    min_pw_high_ns = None

    if pvt:
        cell_fall_ns   = tt_25_5v_delay(pvt)
        wc             = worst_case_delay(pvt)
        min_pw_high_ns = wc if wc else None

    if cell_fall_ns is None:
        cell_fall_ns = FALLBACK_CELL_FALL_NS.get(name, 0.350)
        print(f'  [{name}] WARNING: no PVT JSON; using fallback {cell_fall_ns:.3f} ns',
              file=sys.stderr)

    if min_pw_high_ns is None:
        min_pw_high_ns = cell_fall_ns * 1.60   # SS/125°C typically ~1.6× TT

    arts   = desc.get('artifacts', {})
    lib_rel = arts.get('liberty_out', f'../cells/lsdl_basic/{name}.lib')
    out_path = (desc_path.parent / lib_rel).resolve()

    cell_text = emit_cell(desc, cell_fall_ns, min_pw_high_ns)
    print(f'  [{name}] cell_fall={cell_fall_ns*1000:.0f}ps  '
          f'min_pw_high={min_pw_high_ns*1000:.0f}ps')
    return name, cell_text, out_path


# ── main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('descriptors', nargs='*', type=Path,
                    help='YAML descriptor path(s). Omit with --all.')
    ap.add_argument('--all', action='store_true',
                    help='Process every descriptor/*.yaml found.')
    ap.add_argument('--output', '-o', type=Path, default=None,
                    help='Combined output .lib path (default: per-cell files).')
    ap.add_argument('--pvt-dir', type=Path, default=PVT_DIR,
                    help='Directory containing *_pvt.json files.')
    args = ap.parse_args()

    desc_paths: list[Path] = list(args.descriptors)
    if args.all:
        desc_paths = sorted(DESC_DIR.glob('*.yaml'))

    if not desc_paths:
        ap.print_usage()
        sys.exit(1)

    results = []
    print('gen_liberty.py — generating Liberty')
    for dp in desc_paths:
        results.append(process_cell(dp, pvt_dir=args.pvt_dir))

    if args.output:
        # Combined file: one library block with all cells.
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, 'w') as f:
            f.write(_HEADER)
            for _, cell_text, _ in results:
                f.write(cell_text)
                f.write('\n')
            f.write(_FOOTER)
        print(f'wrote combined lib: {args.output}')
    else:
        # Per-cell standalone files.
        for name, cell_text, out_path in results:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            with open(out_path, 'w') as f:
                f.write(_HEADER)
                f.write(cell_text)
                f.write('\n')
                f.write(_FOOTER)
            print(f'wrote {out_path}')


if __name__ == '__main__':
    main()
